name: Test - Windows adapter

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-windows:
    name: Windows Python Tests (adapter)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (
            pip install -r requirements.txt
          ) else (
            pip install pytest cantools python-multipart python-can
          )
      - name: Run adapter unit tests
        run: |
          python -m pytest -q backend/tests/test_pcan_adapter.py
          python -m pytest -q backend/tests/test_dbc_api.py || true
