name: Test - Windows adapter

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-windows:
    name: Windows Python Tests (adapter)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path 'requirements.txt') {
            python -m pip install -r requirements.txt
          } else {
            python -m pip install pytest cantools python-multipart python-can
          }
      - name: Run adapter unit tests
        shell: pwsh
        run: |
          python -m pytest -q backend/tests/test_pcan_adapter.py
